---
title: "Untitled"
author: "Joachim Muench"
date: "20 2 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Type: script
# Name: hands-on.R
# Author: Chris Reudenbach, creuden@gmail.com
# Description:  retrieves airborn image data 
#               defines AOI and performs classification tasks
# Dependencies: geoAI.R  
# Output: original rgb tile 
#         AOI window of this tile (research_area)
#         unsupervised classification with kmeans (via RStoolbox)
#         supervised classification recursive partitioning and regression trees (via rpart)
#         random forest (via caret) 
#         superclust (automated random forest via RStoolbox)# Copyright: Chris Reudenbach 2021, GPL (>= 3)
# git clone https://github.com/gisma-courses/courses-scripts/geoAI.git
#------------------------------------------------------------------------------

# 0 - specific setup
#-----------------------------
library(envimaR)
source(file.path(envimaR::alternativeEnvi(root_folder = "C:/Users/jomue/edu/geoAI",
                                          alt_env_id = "COMPUTERNAME",
                                          alt_env_value = "PCRZP",
                                          alt_env_root_folder = "F:/BEN/edu/geoAI"),
                 "src/000-rspatial-setup.R"))


# add define project specific subfolders
appendProjectDirList = c("data/sentinel/",
                         "data/vector_data/",
                         "data/sentinel/S2/",
                         "data/sentinel/SAFE/",
                         "data/sentinel/research_area/")

 # 2 - define variables
       #---------------------
       
      
       
       # creating a raster stack
       stack=raster::stack(paste0(envrmt$path_doc,"/marburg_dop.tif"))
       # airborn image true and false color composite 
       mapview::viewRGB(stack, r = 4, g = 3, b = 2)    

       train_area <- mapview::viewRGB(stack, r = 4, g = 4, b = 3) %>% mapedit::editMap() 
       # add class (building) and id (integer number)
       building <- train_area$finished$geometry %>% st_sf() %>% mutate(class = "building", id = 1)

       train_area <- mapview::viewRGB(stack, r = 4, g = 3, b = 2) %>% mapedit::editMap()       #add class(field) and id
       fields <- train_area$finished$geometry %>% st_sf() %>% mutate(class = "fields", id = 2) 

       train_area <- mapview::viewRGB(stack, r = 4, g = 3, b = 2) %>% mapedit::editMap()      # add class(meadow) and id
       meadows <- train_area$finished$geometry %>% st_sf() %>% mutate(class = "meadows", id = 3)

       train_area <- mapview::viewRGB(stack, r = 4, g = 4, b = 3) %>% mapedit::editMap()      # add class(forest) and id
       forest <- train_area$finished$geometry %>% st_sf() %>% mutate(class = "forest", id = 4) 

       train_area <- mapview::viewRGB(stack, r = 4, g = 4, b = 3) %>% mapedit::editMap()
# add class(road) and id
       road <- train_area$finished$geometry %>% st_sf() %>% mutate(class = "road", id = 5) 
 # bind it together to one file
       train_areas <- rbind(building, fields, meadows, forest, road)
 # save results
       saveRDS(train_areas, paste0(envrmt$path_doc,"/train_areas_marburg.rds"))
# first we have to project the data into the correct crs
       tp = sf::st_transform(train_areas,crs = sf::st_crs(stack))
 ## next we extract the values from every band of the raster stack 
       # we force the values to be returned as an data frame
       # because extracting the raster way is very slow
       DF <- raster::extract(stack, tp, df=TRUE) 
# we rename the layers for simplicity
       names(DF) = c("id","red","green","blue","nir")
# now we add the "class" category which we need later on for training
# it was dropped during extraction
       DF_sf =st_as_sf(inner_join(DF,tp))  
# finally we produce a simple data frame without geometry
       DF2 = DF_sf
   st_geometry(DF2)=NULL 
## k-means via RStoolbox
       prediction_kmeans = unsuperClass(stack, nSamples = 25000, nClasses = 5, nStarts = 25,
                                        nIter = 250, norm = TRUE, clusterMap = TRUE,
                                        algorithm = "MacQueen")   
mapview(prediction_kmeans$map, col = c('darkgreen', 'burlywood', 'green', 'orange'))
# defining the model 
       cart <- rpart(as.factor(DF2$class)~., data=DF2[,2:5], method = 'class') # the tree
 rpart.plot(cart, box.palette = 0, main = "Classification Tree")  
 prediction_cart <- raster::predict(stack, cart, type='class', progress = 'text') 

